FROM mongo:4.2.6

ENV MONGO_INITDB_ROOT_USERNAME admin
ENV MONGO_INITDB_ROOT_PASSWORD password
ENV MONGO_INITDB_DATABASE vts

COPY setup.js /docker-entrypoint-initdb.d/

#CMD tail -f /dev/null

# docker build . -t mongodb
# docker run -p 27017:27017 mongodb:latest mongod