FROM oraclelinux:7-slim
USER root

RUN  yum -y install oracle-release-el7 oracle-nodejs-release-el7 && \
     yum-config-manager --disable ol7_developer_EPEL && \
     yum -y install oracle-instantclient19.3-basiclite nodejs && \
     rm -rf /var/cache/yum

RUN yum -y install git

# create a directory to shove the code into
RUN mkdir /vts
RUN mkdir /logs

# clone branch
RUN git clone -b master https://github.com/dhlevi/vts.git /vts

WORKDIR /vts/vts-engine

RUN npm install

WORKDIR /
COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]

# CMD tail -f /dev/null

# docker build . -t vts-engine
# docker run --name vts_engine -p 8899:8899 -e PORT=8899 -e ID=SuperEngine -e ROUTE=http://localhost:8899 -e MONGO_CONNECTION="mongodb://admin:password@<container-ip>:27017/vts?authSource=admin" vts-engine:latest
# Get your mongodb IP from: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container name>
# If you used the docker file here, it'll be vts_mongo