FROM alpine:latest
USER root

# install curl
RUN apk update \
    && apk add --update curl rsync \
    && rm -rf /var/cache/apk/* \
    && apk upgrade

# install nodejs, npm
RUN apk add --update npm \
# install git
    && apk add --no-cache bash git openssh

# create a directory to shove the code into
RUN mkdir /vts
RUN mkdir /logs

# clone branch
RUN git clone -b master https://github.com/dhlevi/vts.git /vts

COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]

# CMD tail -f /dev/null

# docker build . -t vts
# docker run -p 9988:9988 -e PORT=9988 -e MONGO_CONNECTION=mongodb://admin:password@localhost:27017/vts vts:latest